app_name="UO Outlands"
appimage_file_name="UO-Outlands"
app_id="uooutlands"
data_dir_name="uooutlands"
proton_version="GE-Proton10-16"
proton_url="https://github.com/GloriousEggroll/proton-ge-custom/releases/download/${proton_version}/${proton_version}.tar.gz"
outlands_url="https://patch.uooutlands.com/download"
min_free_space_mb=4096
